name: Smoke tests (replica set)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  smoke-test-replset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Start Mongo replica set (docker)
        run: |
          docker run -d --name mongo-rs -p 27017:27017 mongo:5.0 --replSet rs0 --bind_ip_all
          # wait for mongod to be up
          for i in 1 2 3 4 5 6 7 8 9 10; do
            docker exec mongo-rs mongo --eval "db.adminCommand('ping')" && break || sleep 2
          done
          docker exec mongo-rs mongo --eval "rs.initiate({_id:'rs0',members:[{_id:0,host:'localhost:27017'}]})" || true
          # wait until PRIMARY
          for i in {1..30}; do
            state=$(docker exec mongo-rs mongo --quiet --eval "rs.status().myState") || true
            if [ "$state" = "1" ]; then
              echo "replica set primary ready"
              break
            fi
            sleep 1
          done

      - name: Install dependencies
        run: npm ci

      - name: Build Next app
        env:
          MONGODB_URI: mongodb://localhost:27017/chocoweb-test?replicaSet=rs0
        run: npm run build

      - name: Start Next server
        env:
          NODE_ENV: production
          MONGODB_URI: mongodb://localhost:27017/chocoweb-test?replicaSet=rs0
        run: |
          nohup npm run start > server.log 2>&1 &

      - name: Wait for server
        run: npx wait-on http://localhost:3000 --timeout 60000

      - name: Run smoke test
        env:
          MONGODB_URI: mongodb://localhost:27017/chocoweb-test?replicaSet=rs0
          BASE_URL: http://localhost:3000
        run: npx tsx scripts/smoke-test.ts

      - name: Upload server log on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: server-log
          path: server.log
